Ipsi/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ipsi.Models;
using Ipsi.Services;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Text;
using Ipsi.Config;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace Ipsi.Controllers
{
    public class AuthController : Controller
    {
        private LoginService loginService;

        public AuthController()
        {
            loginService = new LoginService();
        }
        public IActionResult Login()
        {
            if (!User.Identity.IsAuthenticated)
            {
                foreach (var cookieKey in Request.Cookies.Keys)
                {
                    Response.Cookies.Delete(cookieKey);
                }
            }



            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginInfo loginInfo)
        {


            // loginInfo.Id = loginInfo.UserID;
            // loginInfo.Password = IpsiDataConfig.UserPassword;

            loginInfo.APIKey = IpsiDataConfig.ApiKey;
            loginInfo.isEmployeeLogin = true;

            var result = await this.loginService.Login(loginInfo);

            CookieOptions option = new CookieOptions();

            option.Expires = DateTime.Now.AddDays(1);




            var data = this.GetPrincipalFromExpiredToken(result.JwtToken);

            var claimsIdentity = new ClaimsIdentity(
            data.Claims,
            CookieAuthenticationDefaults.AuthenticationScheme);

            // await HttpContext.SignInAsync(
            //     CookieAuthenticationDefaults.AuthenticationScheme,
            //     new ClaimsPrincipal(claimsIdentity));

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                new AuthenticationProperties
                {
                    IsPersistent = true,
                    ExpiresUtc = DateTime.UtcNow.AddHours(1)
                });




            if (result.UserId != null)
            {
                Response.Cookies.Append("JwtToken", result.JwtToken, option);
                Response.Cookies.Append("RefreshToken", result.RefreshToken, option);
                Response.Cookies.Append("UserType", result.UserType.ToString(), option);
                Response.Cookies.Append("UserId", result.UserId, option);
                Response.Cookies.Append("UserName", result.UserName, option);
            }


            return RedirectToAction("UserInfo");
        }

        [Authorize]
        public IActionResult UserInfo()
        {
            var Name = User.Identity.Name;
            var authenticationType = User.Identity.AuthenticationType;
            var isAuthenticated = User.Identity.IsAuthenticated;


            string RefreshToken = "None";

            if (Request.Cookies["RefreshToken"] != null)
            {
                RefreshToken = Request.Cookies["RefreshToken"].ToString();
            }
            string UserName = "None";
            if (isAuthenticated)
            {
                UserName = User.Claims.SingleOrDefault(x => x.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").Value;
            }




            ViewData["Message"] = string.Format("Name : {0}, authenticationType : {1}, isAuthenticated : {2}, Name : {3}, RefreshToken : {4}",
            Name, authenticationType, isAuthenticated, UserName, RefreshToken);//

            // User.Identity.Name

            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(
                CookieAuthenticationDefaults.AuthenticationScheme);

            foreach (var cookieKey in Request.Cookies.Keys)
            {
                Response.Cookies.Delete(cookieKey);
            }

            ViewData["Message"] = "로그아웃 되었습니다.";
            return View();
        }

        private ClaimsPrincipal GetPrincipalFromExpiredToken(string token)
        {
            var tokenValidationParameters = new TokenValidationParameters
            {
                ValidateAudience = false, //you might want to validate the audience and issuer depending on your use case
                ValidateIssuer = false,
                ValidateIssuerSigningKey = true,
                IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(IpsiDataConfig.JwtKey)),
                ValidateLifetime = true //here we are saying that we don't care about the token's expiration date
            };

            var tokenHandler = new JwtSecurityTokenHandler();
            SecurityToken securityToken;
            var principal = tokenHandler.ValidateToken(token, tokenValidationParameters, out securityToken);
            var jwtSecurityToken = securityToken as JwtSecurityToken;
            if (jwtSecurityToken == null || !jwtSecurityToken.Header.Alg.Equals(SecurityAlgorithms.HmacSha256, StringComparison.InvariantCultureIgnoreCase))
                throw new SecurityTokenException("Invalid token");

            return principal;
        }
    }
}

Ipsi/Controllers/ExcelController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Ipsi.Models;
using Ipsi.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;

namespace Ipsi.Controllers
{
    // [Authorize]
    public class ExcelController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        private ExcelService excelService;
        public ExcelController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            excelService = new ExcelService();
        }


        public async Task<IActionResult> Export()
        {
            string sWebRootFolder = _hostingEnvironment.WebRootPath;
            string sFileName = @"demo.xlsx";
            string URL = string.Format("{0}://{1}/{2}", Request.Scheme, Request.Host, sFileName);

            TestModel model1 = new TestModel();
            model1.Id = 1;
            model1.Emp_No = "011";
            model1.Name = "홍길동";
            model1.Age = 28;
            model1.Dept = "정보전산과";

            TestModel model2 = new TestModel();
            model2.Id = 2;
            model2.Emp_No = "012";
            model2.Name = "이순신";
            model2.Age = 33;
            model2.Dept = "입학관리과";

            TestModel model3 = new TestModel();
            model3.Id = 3;
            model3.Emp_No = "013";
            model3.Name = "권율";
            model3.Age = 47;
            model3.Dept = "경리과";

            List<TestModel> list = new List<TestModel>();
            list.Add(model1);
            list.Add(model2);
            list.Add(model3);

            return File(await excelService.Export(sWebRootFolder, sFileName, list), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sFileName);
        }

        public IActionResult Import()
        {
            return View();
        }


        [HttpPost]
        public IActionResult ImportExcel()
        {
            IFormFile file = Request.Form.Files[0];
            string folderName = "Upload";
            string webRootPath = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(webRootPath, folderName);
            StringBuilder sb = new StringBuilder();
            if (!Directory.Exists(newPath))
            {
                Directory.CreateDirectory(newPath);
            }
            if (file.Length > 0)
            {
                string sFileExtension = Path.GetExtension(file.FileName).ToLower();
                ISheet sheet;
                string fullPath = Path.Combine(newPath, file.FileName);
                using (var stream = new FileStream(fullPath, FileMode.Create))
                {
                    file.CopyTo(stream);
                    stream.Position = 0;
                    if (sFileExtension == ".xls")
                    {
                        HSSFWorkbook hssfwb = new HSSFWorkbook(stream); //This will read the Excel 97-2000 formats  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook  
                    }
                    else
                    {
                        XSSFWorkbook hssfwb = new XSSFWorkbook(stream); //This will read 2007 Excel format  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook   
                    }


                    IRow headerRow = sheet.GetRow(0); //Get Header Row
                    int cellCount = headerRow.LastCellNum;

                    sb.Append("<table id='test'><tr>");
                    for (int j = 0; j < cellCount; j++)
                    {
                        NPOI.SS.UserModel.ICell cell = headerRow.GetCell(j);
                        if (cell == null || string.IsNullOrWhiteSpace(cell.ToString())) continue;
                        sb.Append("<th>" + cell.ToString() + "</th>");
                    }
                    sb.Append("</tr>");
                    sb.AppendLine("<tr>");
                    for (int i = (sheet.FirstRowNum + 1); i <= sheet.LastRowNum; i++) //Read Excel File
                    {
                        IRow row = sheet.GetRow(i);
                        if (row == null) continue;
                        if (row.Cells.All(d => d.CellType == CellType.Blank)) continue;
                        for (int j = row.FirstCellNum; j < cellCount; j++)
                        {
                            if (row.GetCell(j) != null)
                                sb.Append("<td>" + row.GetCell(j).ToString() + "</td>");
                        }
                        sb.AppendLine("</tr>");
                    }
                    sb.Append("</table>");
                }
            }
            return this.Content(sb.ToString());
        }
    }
}

Ipsi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ipsi</title>

    <script src="~/lib/datatables/jQuery-3.3.1/jquery-3.3.1.js"></script>
    <script src="~/lib/bootstrap/bootstrap-4.1.3-dist/js/bootstrap.js"></script>
    <script src="~/lib/datatables/DataTables-1.10.18/js/jquery.dataTables.js"></script>
    <script src="~/lib/datatables/DataTables-1.10.18/js/dataTables.bootstrap4.js"></script>

    
    <script src="~/lib/datatables/Responsive-2.2.2/js/dataTables.responsive.min.js"></script>
    <script src="~/lib/datatables/Responsive-2.2.2/js/responsive.bootstrap4.min.js"></script>
    <script src="~/lib/datatables/Buttons-1.5.4/js/dataTables.buttons.min.js"></script>
    <script src="~/lib/datatables/Buttons-1.5.4/js/buttons.html5.min.js"></script>
    <script src="~/lib/datatables/Buttons-1.5.4/js/buttons.bootstrap4.min.js"></script>
    <script src="~/lib/datatables/Buttons-1.5.4/js/buttons.print.min.js"></script>    
    <script src="~/lib/datatables/Buttons-1.5.4/js/buttons.colVis.min.js"></script>    
    
    <script src="~/lib/datatables/JSZip-2.5.0/jszip.min.js"></script>
    <script src="~/lib/datatables/pdfmake-0.1.36/pdfmake.min.js"></script>
    <script src="~/lib/datatables/pdfmake-0.1.36/vfs_fonts.js"></script>
    
    <script src="~/js/site.js"></script>

    <!-- CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap-4.1.3-dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/datatables/DataTables-1.10.18/css/dataTables.bootstrap4.css" />
    <link rel="stylesheet" href="~/lib/datatables/Responsive-2.2.2/css/responsive.bootstrap4.min.css" />
    <link rel="stylesheet" href="~/lib/datatables/Buttons-1.5.4/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/datatables/Buttons-1.5.4/css/buttons.bootstrap4.min.css" />

    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/offcanvas.css" />
    
    

   
</head>
<body>
    
    <partial name="~/Views/Shared/_Nav.cshtml" />

    


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Ipsi</p>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

Ipsi/Views/Shared/_nav.cshtml
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <a class="navbar-brand mr-auto mr-lg-0" href="#">입시 종합정보</a>
  <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
      </li>
      <li class="nav-item">
        <a asp-area="" asp-controller="Auth" asp-action="UserInfo" class="nav-link">UserInfo</a>
      </li>
      <li class="nav-item">
        <a asp-area="" asp-controller="Excel" asp-action="Export" class="nav-link">Excel Export</a>
      </li>
      <li class="nav-item">
        <a asp-area="" asp-controller="Excel" asp-action="Import" class="nav-link">Excel Import</a>
      </li>
    </ul>
    <div><a asp-area="" asp-controller="Auth" asp-action="Logout" class="btn btn-outline-primary my-2 my-sm-0" >로그아웃</a></div>>
  </div>
</nav>


<script>
  $( document ).ready(function() {
    $('[data-toggle="offcanvas"]').on('click', function () {
      $('.offcanvas-collapse').toggleClass('open')
    });
  });
  
</script>